name: calculetor
description: "A new Flutter project."
publish_to: "none"
version: 1.2.0+3

environment:
  sdk: ">=3.3.1 <4.0.0"
dependencies:

  flutter:
    sdk: flutter
  icons_launcher: ^3.0.0
  flutter_lints:
  flutter_staggered_grid_view:
  image_picker: 
  math_expressions: 
  permission_handler: 
  shared_preferences:   
  auto_size_text: 
  better_player_enhanced: 
  cached_network_image: 
  camera: 
  flutter_markdown: 
  url_launcher: 
  http:
  package_info_plus:
  intl:
  font_awesome_flutter:
  share_plus:
  video_thumbnail: ^0.5.6
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


icons_launcher:
  image_path: "assets/calculetor1.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - CHANGELOG.md
    - assets/calculetor1.png